# Generated by Django 2.2.5 on 2019-09-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='articl',
        ),
    ]
