# Generated by Django 2.2.5 on 2019-09-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190915_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
