# Generated by Django 2.2.5 on 2019-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='template',
            field=models.FileField(upload_to='guide/'),
        ),
    ]
