# Generated by Django 2.2.5 on 2019-09-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0002_auto_20190917_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='template',
            field=models.FileField(upload_to='guides/'),
        ),
    ]
