# Generated by Django 2.2.5 on 2019-09-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0003_auto_20190917_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
