# Generated by Django 2.2.5 on 2019-09-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0004_guide_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='guide_file',
            field=models.FileField(blank=True, null=True, upload_to='guides/'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='template',
            field=models.FileField(upload_to='templates/'),
        ),
    ]
