# Generated by Django 2.2.5 on 2019-09-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0005_auto_20190918_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='template',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
