# Generated by Django 2.2.5 on 2019-09-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0006_auto_20190918_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_file',
            field=models.FileField(upload_to='guides/'),
        ),
    ]
