# Generated by Django 2.2.5 on 2019-09-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.CharField(max_length=200),
        ),
    ]
