# Generated by Django 2.2.5 on 2019-09-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_auto_20190910_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='user',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
