# Generated by Django 2.2.5 on 2019-09-17 09:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('participants', models.TextField()),
                ('objectives', ckeditor.fields.RichTextField()),
                ('recommendations', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
            ],
        ),
    ]
